name: Build APK for Simple-updates

on:
  push:
    branches:
      - Simple-updates
      - updates
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Debug Vite config
        run: cat vite.config.js
        
      - name: Build web assets
        run: npm run build --verbose
        
      - name: Check build output
        run: |
          ls -la
          echo "Checking dist directory:"
          ls -la dist || echo "dist directory does not exist"
        
      - name: Run Capacitor sync
        run: npx cap sync android
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
        
      - name: Build APK
        working-directory: ./android
        run: ./gradlew assembleDebug
        
      - name: Check APK exists
        run: |
          echo "Checking if APK exists:"
          ls -la android/app/build/outputs/apk/debug/ || echo "Debug APK directory does not exist"
        
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: android/app/build/outputs/apk/debug/app-debug.apk
          name: Simple-updates Build ${{ github.run_number }}
          tag_name: simple-updates-${{ github.run_number }}
          draft: false
          prerelease: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}