name: Build and Release New-Features Debug Apk

on:
  push:
    branches:
      - new-features
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build and Release Debug Apk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Extract version from package.json
      - name: Get Version from package.json
        id: package_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      # Generate timestamp for uniqueness
      - name: Generate Timestamp
        id: timestamp
        run: echo "DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      # Generate release tag dynamically - ensure valid tag format
      - name: Generate Release Tag
        id: release_tag
        run: |
          # Create a valid tag name (no spaces, no special chars except .-_)
          RELEASE_TAG="v${{ steps.package_version.outputs.VERSION }}-${{ steps.timestamp.outputs.DATE }}"
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_OUTPUT

      # Build the React app
      - name: Build React app
        run: npm run build

      # Install Capacitor CLI if not installed globally
      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      # Sync React build with Android platform
      - name: Sync Capacitor with Android
        run: npx cap sync android

      # Setup Java for Android build
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Grant execute permissions for Gradle wrapper
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x android/gradlew

      # Build Debug APK
      - name: Build Debug APK
        run: cd android && ./gradlew assembleDebug

      # Create a Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "New-Features Release ${{ steps.package_version.outputs.VERSION }}"
          files: android/app/build/outputs/apk/debug/app-debug.apk
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}