name: Build, Sign and Release to Zap.Store

on:
  push:
    branches:
      - Simple-updates
      - updates1 # Added feed branch to automatically trigger the workflow
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build, Sign and Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Extract version from package.json
      - name: Get Version from package.json
        id: package_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      # Generate timestamp for uniqueness
      - name: Generate Timestamp
        id: timestamp
        run: echo "DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      # Generate release tag dynamically
      - name: Generate Release Tag
        id: release_tag
        run: echo "RELEASE_TAG=feed-${{ env.VERSION }}-${{ env.DATE }}" >> $GITHUB_ENV

      # Build the React app
      - name: Build React app
        run: npm run build

      # Install Capacitor CLI if not installed globally
      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      # Generate keystore for signing
      - name: Generate Keystore
        id: generate_keystore
        run: |
          echo "==== GENERATING NEW KEYSTORE ===="
          # Print current directory for debugging
          echo "Current directory: $(pwd)"
          
          echo "Generating new keystore for signing..."
          keytool -genkey -v -keystore release.keystore \
            -alias ${{ secrets.KEY_ALIAS }} \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass ${{ secrets.KEY_STORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            -dname "cn=Unknown, ou=Unknown, o=Unknown, c=US"
          
          # Verify keystore was created
          if [ -f "release.keystore" ]; then
            echo "✅ Keystore file created successfully"
            echo "Keystore size: $(wc -c release.keystore | awk '{print $1}') bytes"
            ls -la release.keystore
            
            # Generate base64 for signing step
            base64 release.keystore > release.keystore.base64
            
            # Make a copy of the keystore in android/app/ directory
            mkdir -p android/app/
            cp release.keystore android/app/release.keystore
            echo "Copied keystore to android/app/release.keystore"
            
            # Set the keystore base64 as an output and remove newlines
            echo "keystore_base64=$(cat release.keystore.base64 | tr -d '\n')" >> $GITHUB_OUTPUT
          else
            echo "❌ FAILED to create keystore file!"
            exit 1
          fi
          
          echo "==== KEYSTORE GENERATION COMPLETE ===="

      # Sync React build with Android platform
      - name: Sync Capacitor with Android
        run: npx cap sync android

      # Prepare Android project
      - name: Prepare Android Project
        run: |
          echo "==== PREPARING ANDROID PROJECT ===="
          
          # Print current directory for debugging
          echo "Current directory: $(pwd)"
          
          # Verify android directory exists
          ls -la
          
          # Check if android/ directory exists
          if [ ! -d "android" ]; then
            echo "ERROR: Android directory not found. Did capacitor sync fail?"
            exit 1
          fi
          
          # Check app/build.gradle exists
          if [ ! -f "android/app/build.gradle" ]; then
            echo "ERROR: android/app/build.gradle not found. Project structure issue."
            ls -la android/
            exit 1
          fi
          
          # Ensure signing config exists in build.gradle
          echo "Checking signing config in build.gradle..."
          if ! grep -q "signingConfigs" android/app/build.gradle; then
            echo "Adding signing configuration to build.gradle"
            
            # Create backup
            cp android/app/build.gradle android/app/build.gradle.bak
            
            # Inject signing config
            sed -i '/defaultConfig {/,/}/a\\n    signingConfigs {\n        release {\n            storeFile file("release.keystore")\n            storePassword "'${{ secrets.KEY_STORE_PASSWORD }}'"\n            keyAlias "'${{ secrets.KEY_ALIAS }}'"\n            keyPassword "'${{ secrets.KEY_PASSWORD }}'"\n        }\n    }' android/app/build.gradle
            
            # Reference signing config in buildTypes
            sed -i '/release {/,/}/s/}/    signingConfig signingConfigs.release\n}/' android/app/build.gradle
          else
            echo "Signing config already exists in build.gradle"
          fi
          
          # Verify keystore file exists in android/app/
          if [ -f "android/app/release.keystore" ]; then
            echo "✅ Keystore file exists in android/app/"
          else
            echo "WARNING: Keystore not found in android/app/, copying again..."
            cp release.keystore android/app/release.keystore
          fi
          
          # Create keystore.properties (as an additional way to provide keystore info)
          echo "Creating keystore.properties..."
          cat > android/keystore.properties << EOF
          storePassword=${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=release.keystore
          EOF
          
          echo "==== ANDROID PROJECT READY ===="

      # Setup Java for Android build - changed to JDK 17 for compatibility with Zap.Store
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Verify JDK version and make sure it's visible
      - name: Verify Java version
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          echo "PATH=$PATH"
          echo "Java version:"
          java -version
          echo "Javac version:"
          javac -version
          echo "All java installations:"
          which java || echo "No java found"
          ls -la $JAVA_HOME/bin/ || echo "No JAVA_HOME/bin directory"

      # Setup Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Grant execute permissions for Gradle wrapper
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./android/gradlew

      # Fix Java version - simplified approach
      - name: Prepare Java 17 environment
        run: |
          echo "=== Setting up Java 17 compatibility ==="
          
          # Create gradle.properties with Java 17 settings
          cat > android/gradle.properties << EOF
          # Java 17 settings
          org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --add-opens java.base/java.io=ALL-UNNAMED
          org.gradle.java.home=${JAVA_HOME}
          android.useAndroidX=true
          kotlin.jvm.target.validation.mode=warning
          # Debug settings
          org.gradle.logging.level=debug
          EOF
          
          echo "=== Java setup complete ==="

      # Build Release APK instead of Debug
      - name: Build Release APK
        id: build_apk
        # Change to false to immediately see build failures
        continue-on-error: false
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        run: |
          cd android
          
          # Print detailed info for debugging
          echo "==== ENVIRONMENT INFO ===="
          echo "JAVA_HOME = $JAVA_HOME"
          echo "Android SDK = $ANDROID_SDK_ROOT"
          echo "=========================="
          
          # Print information about gradle file
          echo "==== GRADLE CONFIG INFO ===="
          cat app/build.gradle
          echo "============================="
          
          # Check all possible flavor/variant combinations to see what's available
          echo "==== GRADLE TASKS ===="
          ./gradlew tasks --group="build"
          echo "======================="
          
          # Build with more basic settings first
          echo "==== BUILDING DEBUG APK FIRST AS TEST ===="
          ./gradlew assembleDebug --info
          ls -la app/build/outputs/apk/debug/
          echo "=========================================="
          
          # Then try the release build
          echo "==== BUILDING RELEASE APK ===="
          ./gradlew \
            -Dorg.gradle.java.home="$JAVA_HOME" \
            assembleRelease --info
          
          # Check where the APK was actually built
          echo "==== SEARCHING FOR APK FILES ===="
          find . -name "*.apk" -type f | sort
          
          # If we can't find any APKs, that's a failure
          if [ $(find . -name "*.apk" -type f | wc -l) -eq 0 ]; then
            echo "ERROR: No APK files were generated. Build failed."
            exit 1
          fi

      # Properly locate and prepare APK for signing
      - name: Locate and Prepare APK for Signing
        id: locate_apk
        run: |
          echo "Locating APK files..."
          
          # Find all APK files
          APK_FILES=$(find android -name "*.apk" -type f | sort)
          echo "Found these APK files:"
          echo "$APK_FILES"
          
          # Find the main release APK
          RELEASE_APK=$(find android -name "*release*.apk" -type f | grep -v "unsigned" | head -n 1)
          
          # If no release APK found, use the first APK
          if [ -z "$RELEASE_APK" ]; then
            echo "No specific release APK found, using the first APK found"
            RELEASE_APK=$(echo "$APK_FILES" | head -n 1)
          fi
          
          if [ -z "$RELEASE_APK" ]; then
            echo "No APK files found. This shouldn't happen as build step should have failed."
            exit 1
          fi
          
          echo "Using APK: $RELEASE_APK"
          
          # Create the directory expected by the sign-android-release action
          mkdir -p android/app/build/outputs/apk/release
          
          # Copy to the expected location
          cp "$RELEASE_APK" android/app/build/outputs/apk/release/app-release-unsigned.apk
          
          echo "APK prepared for signing at: android/app/build/outputs/apk/release/app-release-unsigned.apk"
          echo "apk_path=android/app/build/outputs/apk/release" >> $GITHUB_OUTPUT

      # Verify APK exists before signing - we don't need this anymore since we've handled it in the locate_apk step
      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ${{ steps.locate_apk.outputs.apk_path }}
          signingKeyBase64: ${{ steps.generate_keystore.outputs.keystore_base64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
          
      # Verify signed APK exists
      - name: Verify Signed APK
        run: |
          if [ -z "${{ steps.sign_app.outputs.signedReleaseFile }}" ]; then
            echo "::error::No signed APK was produced. Check signing step output."
            exit 1
          else
            echo "Signed APK successfully created at: ${{ steps.sign_app.outputs.signedReleaseFile }}"
            ls -la "${{ steps.sign_app.outputs.signedReleaseFile }}"
          fi

      # Create a Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: 'Release ${{ env.RELEASE_TAG }}'
          draft: false
          prerelease: true

      # Upload Signed APK to Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.sign_app.outputs.signedReleaseFile }}
          asset_name: app-release-signed.apk
          asset_content_type: application/vnd.android.package-archive

      # Setup for Zap.Store publishing
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.5
      
      - name: Install Apktool
        run: |
          wget "https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool"
          wget "https://github.com/iBotPeaches/Apktool/releases/download/v2.10.0/apktool_2.10.0.jar"
          mv apktool_2.10.0.jar apktool.jar
          sudo cp apktool /usr/local/bin
          sudo cp apktool.jar /usr/local/bin
          sudo chmod +x /usr/local/bin/apktool
          sudo chmod +x /usr/local/bin/apktool.jar
      
      - name: Get Zap.Store CLI
        run: |
          mkdir -p /home/runner/.zapstore
          git clone https://github.com/zapstore/zapstore-cli.git
          cd zapstore-cli
          git fetch --tags
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/zapstore/zapstore-cli/releases/latest)
          TAG_NAME=$(echo $LATEST_RELEASE | jq -r .tag_name)
          git checkout $TAG_NAME
          dart pub get
          dart compile exe lib/main.dart -o build
      
      - name: Publish to Zap.Store
        env:
          NSEC: ${{ secrets.NSEC }}
        run: |
          cd $GITHUB_WORKSPACE
          APKSIGNER_PATH=$ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner ./zapstore-cli/build publish "RUNSTR"